- platform: mqtt
  name: "Jeff Destination"
  state_topic: "jeff/driving/destination"
- platform: template
  sensors:
    family_presence:
      friendly_name: Family Presence
      unit_of_measurement: ''
      value_template: >-
          {%- if is_state("sensor.jeff_presence", "present") %}
                Home
            {% elif is_state("sensor.kat_presence", "present") %}
                Home
            {% else %}
                Away
            {%- endif %}
      icon_template: >-
        {%- if is_state("sensor.family_presence", "Home") %}
          mdi:home
        {%- elif is_state("sensor.family_presence", "Away") %}
          mdi:home-outline
        {% else %}
          mdi:sync-alert
        {%- endif %}
